export const preview_dialogue = {
    'preview_dialogue': {
        'annotation_tasks': [],
        'bot_persona': [],
        'dialogue_id': 'preview_dialogue',
        'turns': [
            {'text': 'hey', 'agent_idx': 0},
            {'text': 'hey, how are you?', 'agent_idx': 1},
            {'text': 'i\'m doing okay, what about you?', 'agent_idx': 0},
            {'text': 'me too, so what have you been up to', 'agent_idx': 1},
            {'text': 'looking into buying a new car', 'agent_idx': 0},
            {'text': 'that\'s exciting! what are you thinking about getting?', 'agent_idx': 1},
            {'text': 'i really want a tesla', 'agent_idx': 0},
            {'text': 'oh yea, those are pretty cool', 'agent_idx': 1},
            {'text': 'i would have to install a charging station for it at my house though, which sounds like a hassle', 'agent_idx': 0},
            {'text': 'i heard it is pretty easy to do, actually', 'agent_idx': 1},
            {'text': 'oh, really? well, maybe it\'s not as big of a deal as I was thinking then', 'agent_idx': 0},
            {'text': 'yeah, probably not', 'agent_idx': 1},
            {'text': 'have you ever thought about buying a tesla', 'agent_idx': 0},
            {'text': 'kinda. i don\'t need a new car anytime soon, but a tesla would be nice someday', 'agent_idx': 1},
            {'text': 'sure', 'agent_idx': 0},
            {'text': 'anyway, so, you watch any good movies lately?', 'agent_idx': 1},
            {'text': 'i liked the newest spiderman', 'agent_idx': 0},
            {'text': 'which one was that again? something home?', 'agent_idx': 1},
            {'text': 'it was called no way home', 'agent_idx': 0},
            {'text': 'ah i see. Wasn\'t the second movie also like that?', 'agent_idx': 1},
            {'text': 'yeah, I think it was called far from home', 'agent_idx': 0},
            {'text': 'they were trying to be clever, I guess', 'agent_idx': 1},
            {'text': 'probably', 'agent_idx': 0},
            {'text': 'what did you like so much about no way home?', 'agent_idx': 1},
            {'text': 'they introduced a lot of characters that were exciting to see', 'agent_idx': 0},
            {'text': 'oh yeah, I think i heard about that', 'agent_idx': 1},
            {'text': 'people went nuts for it', 'agent_idx': 0},
            {'text': 'I can imagine', 'agent_idx': 1},
            {'text': 'Did you watch any of the earlier ones?', 'agent_idx': 0},
        ],
        turns2: [
            {'text': 'hey', 'agent_idx': 0},
            {'text': 'hi! i am happy to be talking with you. how are you doing?', 'agent_idx': 1},
            {'text': 'i\'m doing great, what about you?', 'agent_idx': 0},
            {'text': 'me too, do you have any exciting plans this weekend?', 'agent_idx': 1},
            {'text': 'looking into buying a new car', 'agent_idx': 0},
            {'text': 'that\'s great! what are you thinking about getting?', 'agent_idx': 1},
            {'text': 'i really want a tesla', 'agent_idx': 0},
            {'text': 'oh i love teslas', 'agent_idx': 1},
            {'text': 'i want it to drive me around autonomously, i hate driving', 'agent_idx': 0},
            {'text': 'that is a pretty great feature!', 'agent_idx': 1},
            {'text': 'it sure is', 'agent_idx': 0},
            {'text': 'so, what hobbies do you have', 'agent_idx': 1},
            {'text': 'i workout a lot', 'agent_idx': 0},
            {'text': 'that is impressive! do you go to the gym?', 'agent_idx': 1},
            {'text': 'yeah most days, sometimes I just run outside', 'agent_idx': 0},
            {'text': 'i used to run a lot but i do not do it so much anymore.', 'agent_idx': 1},
            {'text': 'why not', 'agent_idx': 0},
            {'text': 'i just cannot seem to muster up the motivation', 'agent_idx': 1},
            {'text': 'you should try. it is healthier to exercise. do you do any exercise at all?', 'agent_idx': 0},
            {'text': 'ah uh no', 'agent_idx': 1},
            {'text': 'yeah i definitely recommend getting into some exercise', 'agent_idx': 0},
            {'text': 'okay you are right. i will do my best', 'agent_idx': 1},
            {'text': 'good luck', 'agent_idx': 0},
            {'text': 'thanks i think i will need it. what gym do you go to', 'agent_idx': 1},
            {'text': 'there is a planet fitness by me, so i just go there', 'agent_idx': 0},
            {'text': 'oh i have seen those around. do you like it?', 'agent_idx': 1},
            {'text': 'yeah it is pretty big, at least the one by me is, so there are a lot of options and space', 'agent_idx': 0},
            {'text': 'i would like that too, i wonder if the one i have seen is big. it looks kind of small', 'agent_idx': 1},
            {'text': 'yeah', 'agent_idx': 0},
        ]
    }
}